appearance=dark
desktop_icons_visible=true
desktop_grid_spacing=24
desktop_label_size=15
desktop_icon_scale=1.00
desktop_icon_0_position=2356,405
desktop_icon_1_position=2233,835
desktop_icon_2_position=2213,305
desktop_icon_3_position=2231,485
desktop_icon_4_position=2373,856
desktop_icon_5_position=2392,705
desktop_icon_6_position=2394,552
desktop_icon_7_position=2260,670
dock_scale=1.00
dock_icon_scale=1.00
dock_magnification=true
dock_magnification_scale=1.28
dock_show_indicators=true
dock_order=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
calendar_widget_visible=false
weather_widget_visible=false
calendar_widget_size=small
weather_widget_size=small
cursor_theme=
cursor_size=28
icon_theme=MacTahoe
gtk_theme_light=MacTahoe-Light
gtk_theme_dark=MacTahoe-Dark
dock_apps=__launcher__,org.gnome.Nautilus.desktop,firefox.desktop,org.gnome.Calculator.desktop,org.gnome.TextEditor.desktop,org.gnome.Settings.desktop,org.gnome.Software.desktop,org.gnome.Terminal.desktop,org.gnome.Weather.desktop,__trash__
