appearance=dark
desktop_icons_visible=true
desktop_grid_spacing=24
desktop_label_size=15
desktop_icon_scale=1.00
dock_scale=1.00
dock_icon_scale=1.00
dock_magnification=true
dock_magnification_scale=1.28
dock_show_indicators=true
dock_order=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
calendar_widget_visible=false
weather_widget_visible=false
calendar_widget_size=small
weather_widget_size=small
cursor_theme=
cursor_size=28
