appearance=dark
accent_color=multicolor
text_highlight_automatic=true
icon_widget_style=default
folder_color_automatic=true
sidebar_icon_size=medium
tint_window_background=false
show_scroll_bars=automatic
desktop_icons_visible=true
desktop_grid_spacing=24
desktop_label_size=15
desktop_icon_scale=1.00
desktop_sort_by=none
desktop_use_stacks=true
desktop_label_position=bottom
desktop_show_hard_disks=true
desktop_show_external_disks=true
desktop_show_removable_media=true
desktop_show_servers=true
desktop_icon_0_position=1838,332
desktop_icon_1_position=1816,199
desktop_icon_2_position=1824,52
desktop_icon_3_position=1836,29
dock_scale=0.89
dock_icon_scale=1.00
dock_magnification=true
dock_magnification_scale=1.28
dock_auto_hide=false
dock_position=left
minimize_effect=genie
dock_show_indicators=true
animate_opening_applications=true
dock_order=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
calendar_widget_visible=false
weather_widget_visible=false
calendar_widget_size=large
weather_widget_size=small
cursor_theme=Adwaita
cursor_size=28
icon_theme=Adwaita
gtk_theme_light=Adwaita
gtk_theme_dark=Adwaita-dark
dock_apps=org.gnome.Nautilus,__launcher__,firefox,com.mitchellh.ghostty,org.gnome.Maps.desktop,org.gnome.Loupe.desktop,org.gnome.Calendar.desktop,org.gnome.Contacts.desktop,org.gnome.Software.desktop,org.gnome.Settings.desktop,__trash__
