#!/bin/sh
set -eu

config_home=${XDG_CONFIG_HOME:-"$HOME/.config"}
config_dir="${config_home}/orange"
config_file="${config_dir}/orange.conf"

mkdir -p "$config_dir"
if [ ! -f "$config_file" ]; then
	cp /usr/share/orange/orange.conf "$config_file"
fi

unset GTK_MODULES

export XDG_SESSION_TYPE=${XDG_SESSION_TYPE:-wayland}
export XDG_CURRENT_DESKTOP=${XDG_CURRENT_DESKTOP:-orange}
export XDG_SESSION_DESKTOP=${XDG_SESSION_DESKTOP:-orange}
export DESKTOP_SESSION=${DESKTOP_SESSION:-orange}
export WLR_RENDERER=${WLR_RENDERER:-pixman} #gles2 or vulkan on bare metal, pixman on qemu or virtualbox
export WLR_BACKENDS=${WLR_BACKENDS:-drm,libinput}
export ORANGE_TERMINAL=${ORANGE_TERMINAL:-ghostty}
export GTK_THEME=${GTK_THEME:-Adwaita}
export GTK_ICON_THEME=${GTK_ICON_THEME:-Adwaita}
export XCURSOR_THEME=${XCURSOR_THEME:-Adwaita}
export XCURSOR_SIZE=${XCURSOR_SIZE:-28}
export GDK_BACKEND=${GDK_BACKEND:-wayland}
export QT_QPA_PLATFORM=${QT_QPA_PLATFORM:-wayland}
export SDL_VIDEODRIVER=${SDL_VIDEODRIVER:-wayland}
export CLUTTER_BACKEND=${CLUTTER_BACKEND:-wayland}
export MOZ_ENABLE_WAYLAND=${MOZ_ENABLE_WAYLAND:-1}
export ELECTRON_OZONE_PLATFORM_HINT=${ELECTRON_OZONE_PLATFORM_HINT:-wayland}
export NIXOS_OZONE_WL=${NIXOS_OZONE_WL:-1}


exec /usr/bin/orange \
	--config "$config_file" \
	--assets /usr/share/orange/assets
