#!/bin/sh
set -eu

config_home=${XDG_CONFIG_HOME:-"$HOME/.config"}
config_dir="${config_home}/orange"
config_file="${config_dir}/orange.conf"

mkdir -p "$config_dir"
if [ ! -f "$config_file" ]; then
	cp /usr/share/orange/orange.conf "$config_file"
fi

append_colon_var() {
	name=$1
	value=$2
	eval "current=\${$name-}"
	case ":$current:" in
		*:"$value":*) ;;
		*)
			if [ -n "$current" ]; then
				export "$name=$current:$value"
			else
				export "$name=$value"
			fi
			;;
	esac
}

for appmenu_module in \
	/usr/lib/gtk-3.0/modules/libappmenu-gtk-module.so \
	/usr/lib64/gtk-3.0/modules/libappmenu-gtk-module.so \
	/usr/lib/*/gtk-3.0/modules/libappmenu-gtk-module.so
do
	if [ -f "$appmenu_module" ]; then
		append_colon_var GTK_MODULES appmenu-gtk-module
		break
	fi
done

export XDG_SESSION_TYPE=${XDG_SESSION_TYPE:-wayland}
export XDG_CURRENT_DESKTOP=${XDG_CURRENT_DESKTOP:-orange}
export XDG_SESSION_DESKTOP=${XDG_SESSION_DESKTOP:-orange}
export DESKTOP_SESSION=${DESKTOP_SESSION:-orange}
export WLR_RENDERER=${WLR_RENDERER:-gles2} #gles2 or vulkan on bare metal, pixman on qemu or virtualbox
export WLR_BACKENDS=${WLR_BACKENDS:-drm,libinput}
export ORANGE_TERMINAL=${ORANGE_TERMINAL:-foot}
export GTK_THEME=${GTK_THEME:-Adwaita}
export GTK_ICON_THEME=${GTK_ICON_THEME:-Adwaita}
export XCURSOR_THEME=${XCURSOR_THEME:-Adwaita}
export XCURSOR_SIZE=${XCURSOR_SIZE:-28}
export MOZ_ENABLE_WAYLAND=${MOZ_ENABLE_WAYLAND:-1}


exec /usr/bin/orange \
	--config "$config_file" \
	--assets /usr/share/orange/assets
