#!/bin/sh
exec 2>&1

# Create elogind seat file so sd_seat_can_graphical() returns true.
mkdir -p /run/systemd/seats
cat > /run/systemd/seats/seat0 <<'SEAT'
# This is private data. Do not parse.
CAN_GRAPHICAL=yes
CAN_TTY=yes
SEAT

[ ! -d /run/gdm ] && mkdir -m0711 -p /run/gdm && chown root:gdm /run/gdm
[ ! -d /var/lib/gdm/greeter ] && mkdir -m0755 -p /var/lib/gdm/greeter && chown gdm:gdm /var/lib/gdm/greeter
exec gdm
